#
# Module manifest for module 'PSGet_azMgmtModule'
#
# Generated by: Kit
#
# Generated on: 7/16/2019
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '0ec57fc4-4bea-48e4-ad5f-7911441139fe'

# Author of this module
Author = 'Kit'

# Company or vendor of this module
CompanyName = 'SmallFoxx'

# Copyright statement for this module
Copyright = '© 2019 Kit. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module for managing Azure and Microosft cloud resources with PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; GUID = '17a2feff-488b-47f9-8729-e2cec094624c'; ModuleVersion = '1.5.3'; }, 
               @{ModuleName = 'Az.Resources'; GUID = '48bb344d-4c24-441e-8ea0-589947784700'; ModuleVersion = '1.5.0'; }, 
               @{ModuleName = 'AzureAD'; GUID = 'd60c0004-962d-4dfb-8d28-5707572ffd00'; ModuleVersion = '2.0.2'; },
               @{ModuleName = 'Microsoft.Azure.ActiveDirectory.PIM.PSModule'; GUID = '391177dd-c441-4ae8-bf5e-38a1c0e4e2de'; ModuleVersion = '2.0.0'; },
               @{ModuleName = 'MSOnline'; GUID = 'd162594e-d7aa-42be-9884-84928d3f7acf'; ModuleVersion = '1.1.183'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
# FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
# AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','AzureAD','PIM','Office365','MSOnline'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/smallfoxx/azPimModule/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/smallfoxx/azPimModule/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'iniial release'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = 'https://github.com/smallfoxx/azPimModule'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

